# Generated by Django 3.1.5 on 2021-02-02 15:53

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='education_type',
            field=models.CharField(choices=[('1', 'Graduate'), ('0', 'Not Graduated')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='family_status',
            field=models.CharField(choices=[('1', 'Married'), ('0', 'Not Married')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('0', 'Female')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='housing_type',
            field=models.CharField(choices=[('1', 'Home/Apartment'), ('0', 'Others')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='income_type',
            field=models.CharField(choices=[('0', 'Working'), ('1', 'Student'), ('2', 'Not Working')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='CAD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_status',
            field=models.CharField(default='Decision Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='occupation_type',
            field=models.CharField(choices=[('0', 'IT/Medical/Manager/Secretaries'), ('1', 'Staffs'), ('2', 'Others')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='own_a_car',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='own_a_realty',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No')], default='', max_length=20),
        ),
    ]
