# Generated by Django 3.1.5 on 2021-02-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_auto_20210202_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='account_id',
            field=models.IntegerField(),
        ),
    ]
