# Generated by Django 3.1.5 on 2021-02-11 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0007_stockwatchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTrade',
            fields=[
                ('stocktrade_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_symbol', models.CharField(max_length=20)),
                ('stock_count', models.IntegerField()),
                ('stock_price', models.IntegerField()),
                ('stock_message', models.CharField(default='Initiated', max_length=50)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
