# Generated by Django 3.1.5 on 2021-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_stocktrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktrade',
            name='id',
            field=models.IntegerField(),
        ),
    ]
