# Generated by Django 3.1.5 on 2021-02-12 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Banker', '0005_delete_userprofileinfo'),
        ('Customer', '0009_auto_20210211_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Banker.registercustomers'),
        ),
    ]
