# Generated by Django 3.1.5 on 2021-02-12 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0010_auto_20210212_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='id',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
