# Generated by Django 3.1.5 on 2021-02-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_loanrequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='income_amount',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
