# Generated by Django 3.1.5 on 2021-01-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCustomers',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('sin', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('zipcode', models.CharField(max_length=10)),
                ('contactnumber', models.IntegerField()),
                ('accounttype', models.CharField(choices=[('Savings', 'Savings'), ('Checkings', 'Checkings')], default='Checkings', max_length=12)),
                ('depositamount', models.IntegerField(max_length=12)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
