# Generated by Django 3.1.5 on 2021-02-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banker', '0004_auto_20210201_0559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
