# Generated by Django 3.1.5 on 2021-02-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banker', '0005_delete_userprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercustomers',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
