# Generated by Django 3.1.5 on 2021-02-13 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Banker', '0007_registercustomers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercustomers',
            name='id',
            field=models.ForeignKey(default='890', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
