# Generated by Django 3.1.5 on 2021-02-13 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banker', '0008_auto_20210213_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registercustomers',
            name='id',
        ),
    ]
